### ISSUE TITLE
分布生成器のページの画像がミスリーディング

### ISSUE THREAD

**Issue by lpha-z** [cpprefjp/image#5]
`<random>`ヘッダ中の分布生成器のページには、出力を可視化した図が掲載されています。
しかし、いくつかの図においてはミスリーディングなものになっています。
例えば、[`exponential_distribution`](https://cpprefjp.github.io/reference/random/exponential_distribution.html) は正の値のみを出力するはずですが、[掲載されている図](https://raw.githubusercontent.com/cpprefjp/image/master/reference/random/exponential_distribution/exponential_distribution.png)では負の値の部分にも確率密度があるような可視化になっています。

[掲載されている元データ](https://raw.githubusercontent.com/cpprefjp/image/master/reference/random/exponential_distribution/exponential_distribution.tsv)には負の値はないため、`exponential_distribution`の実装がおかしいのではなく、可視化のスクリプトが原因であると考えています。
おそらく、分布の密度を推定するために使われたアルゴリズム（カーネル密度推定）のせいで密度が広がってしまっているのだと思います。

何とか可視化がこのようなミスリーディングなものにならないようにできないでしょうか。
もしかすると、`exponential_distribution`のような確率密度関数がなめらかでない分布の場合は、単にヒストグラムを表示するようにしたほうがいいのかもしれません。

**Comment by faithandbrave** [comment]
やってみます。
私は乱数や統計の専門家ではないのでおかしいことに気づけていませんでした。

exponential_distribution以外の図でもおかしいところがあったらご指摘いただけると助かります。

**Comment by faithandbrave** [comment]
@lpha-z 
https://github.com/cpprefjp/image/commit/6c721858c1983ab8c5ea3b168ff98c395fa4b6c2
こちらのコミットでヒストグラムの図を追加してみたのですが、いかがでしょう？これでよければ差し替えます。

**Comment by lpha-z** [comment]
返信遅れました。上記6c72185のコミットの図で問題ないと思います。素早い対応ありがとうございます。

他の分布生成器についても確認しました。
次のようにすることを提案します。

### 6c72185のコミットと同様の修正をするとよさそうなもの

#### 離散分布であることが理由のもの

* poisson_distribution

#### 非負の値を出力することが理由のもの

* (exponential_distribution)済
* gamma_distribution
* weibull_distribution
* lognormal_distribution（二つ目の図。以下同様）
* chi_squared_distribution
* fisher_f_distribution

### ミスリーディングではないため、現状維持でよいもの

* extreme_value_distribution
* normal_distribution
* cauchy_distribution
* student_t_distribution
* discrete_distribution（元々ヒストグラムになっているので、そのままでよい）

### その他

* piecewise_constant_distribution（見た目にかなり違和感があるため、6c72185と同様の修正をするほうがよいかもしれない）
* piecewise_linear_distribution（ある意味でミスリーディングではあるが、直感的な理解のためには現状維持がよいかもしれない）

**Comment by faithandbrave** [comment]
weibull_distributionだけ2つ重ねてるので、ヒストグラムだとわかりにくいですね…どうしようかな

**Comment by faithandbrave** [comment]
lognormal_distributionのrscriptが残ってない…。どうやって作ったんだっけ…

**Comment by faithandbrave** [comment]
fisher_f_distributionにあった

**Comment by faithandbrave** [comment]
weibull_distribution以外は直しました。これだけどうすれば…

**Comment by faithandbrave** [comment]
@lpha-z 
weibull_distributionだけ2種類の値を出力していたので、透明なヒストグラムを重ねてみました。これでどうでしょう？
問題なければ差し替えます
https://github.com/cpprefjp/image/commit/36d3df3317994adb2c437208e084898072e599dc

**Comment by lpha-z** [comment]
確認しました。すべて問題ないと思います。weibull_distributionは、単に二枚別々の画像を作ればいいかな、と思いました。

**Comment by faithandbrave** [comment]
welbull_distributionのグラフを、ヒストグラム2つにわけました。
これで一通り完了しました。
問題があったらreopenしてください。
